### ISSUE TITLE
Error when trying to run script

### ISSUE THREAD

**Issue by hnnweb** [zersetz-end/airdcpp-runscript-extension#4]
Adding `/usr/bin/uptime` to try the extension.
But getting an error in the Event log.

Adding it as an schedule.

**Cron schedule:**
`*/1 * * * *`

**Script:**
`/usr/bin/uptime`

```
[runscript:/usr/bin/uptime]SyntaxError: Invalid or unexpected token
    at new Function (<anonymous>)
    at /home/airdc/airdcpp-webclient/config/extensions/airdcpp-runscript-extension/package/dist/webpack:/main.js:30572:1
    at d (/home/airdc/airdcpp-webclient/config/extensions/airdcpp-runscript-extension/package/dist/webpack:/main.js:1:1)
    at Generator._invoke (/home/airdc/airdcpp-webclient/config/extensions/airdcpp-runscript-extension/package/dist/webpack:/main.js:1:1)
    at Generator.forEach.e.<computed> [as next] (/home/airdc/airdcpp-webclient/config/extensions/airdcpp-runscript-extension/package/dist/webpack:/main.js:1:1)
    at n (/home/airdc/airdcpp-webclient/config/extensions/airdcpp-runscript-extension/package/dist/webpack:/main.js:1:1)
    at s (/home/airdc/airdcpp-webclient/config/extensions/airdcpp-runscript-extension/package/dist/webpack:/main.js:1:1)
    at /home/airdc/airdcpp-webclient/config/extensions/airdcpp-runscript-extension/package/dist/webpack:/main.js:1:1
    at new Promise (<anonymous>)
    at /home/airdc/airdcpp-webclient/config/extensions/airdcpp-runscript-extension/package/dist/webpack:/main.js:1:1
```

**Comment by zersetz-end** [comment]
The extension only runs JavaScript script files.
